"""Netscape cookie file helpers for Channel Builder."""

from __future__ import annotations

import time
from http.cookiejar import MozillaCookieJar
from pathlib import Path
from typing import Iterable

import requests


def cookies_path_for_scope(scope: str) -> Path:
    mapping = {
        "youtube": Path("data/cookies/youtube_cookies.txt"),
        "pbs": Path("data/cookies/pbs_cookies.txt"),
        "archive_org": Path("data/cookies/archive_cookies.txt"),
    }
    return mapping.get(scope, Path(f"data/cookies/{scope}_cookies.txt"))


def write_netscape_cookies(path: Path, cookies: Iterable[dict]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by StreamTV Channel Builder"]
    now = int(time.time())
    for cookie in cookies:
        domain = cookie.get("domain", "")
        if not domain:
            continue
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path_attr = cookie.get("path", "/")
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = str(int(cookie.get("expires", now + 86400 * 30)))
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        if not name:
            continue
        lines.append(f"{domain}\t{flag}\t{path_attr}\t{secure}\t{expires}\t{name}\t{value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def session_with_cookie_file(path: Path) -> requests.Session:
    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            )
        }
    )
    if not path.exists():
        return session
    jar = MozillaCookieJar(str(path))
    jar.load(ignore_discard=True, ignore_expires=True)
    session.cookies = jar
    return session


def load_pbs_session() -> requests.Session:
    from streamtv.config import config

    path = Path(config.pbs.cookies_file) if getattr(config, "pbs", None) and config.pbs.cookies_file else cookies_path_for_scope("pbs")
    return session_with_cookie_file(path)
