"""Convert browser-exported YouTube cookies JSON to Netscape cookies.txt for yt-dlp."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# https://curl.haxx.se/rfc/cookie_spec.html\n"
    "# This file was generated by StreamTV. Do not edit.\n"
)


def json_cookies_to_netscape(cookies: list[dict[str, Any]]) -> str:
    lines = [NETSCAPE_HEADER.rstrip("\n")]
    for cookie in cookies:
        domain = (cookie.get("domain") or "").strip()
        name = cookie.get("name") or ""
        if not domain or not name:
            continue
        host_only = bool(cookie.get("hostOnly"))
        path = cookie.get("path") or "/"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        if cookie.get("session") or not cookie.get("expirationDate"):
            expires = "0"
        else:
            expires = str(int(float(cookie["expirationDate"])))
        include_subdomains = "FALSE" if host_only else "TRUE"
        net_domain = domain if domain.startswith(".") or host_only else f".{domain}"
        value = cookie.get("value") or ""
        lines.append(
            f"{net_domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


def write_netscape_from_json(json_path: Path, txt_path: Path) -> Path:
    raw = json.loads(json_path.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise ValueError(f"{json_path}: expected a JSON array of cookies")
    txt_path.parent.mkdir(parents=True, exist_ok=True)
    txt_path.write_text(json_cookies_to_netscape(raw), encoding="utf-8")
    txt_path.chmod(0o600)
    logger.info("Wrote YouTube Netscape cookies: %s (%d entries)", txt_path, len(raw))
    return txt_path


def ensure_netscape_cookies(
    cookies_file: Optional[str],
    cookies_json_file: Optional[str],
) -> Optional[str]:
    """Return Netscape cookies path for yt-dlp, syncing from JSON when newer."""
    json_path = Path(cookies_json_file).expanduser() if cookies_json_file else None
    txt_path = (
        Path(cookies_file).expanduser()
        if cookies_file
        else Path("data/cookies/youtube.com_cookies.txt")
    )

    if json_path and json_path.is_file():
        needs_sync = (
            not txt_path.is_file()
            or json_path.stat().st_mtime > txt_path.stat().st_mtime
        )
        if needs_sync:
            write_netscape_from_json(json_path, txt_path)
        return str(txt_path.resolve())

    if txt_path.is_file():
        return str(txt_path.resolve())
    return cookies_file
